---
dist: trusty

language: java

before_script:
    - sudo apt-get update -q
    - sudo apt-get install -y imagemagick
    - convert -version

after_failure:
    - find build/test-results -name TEST-*.xml | xargs -n 1 sh -c 'echo $0 && cat $0'
