dist: trusty
before_script:
    - sudo apt-get update -q
    - sudo apt-get install ImageMagick=7.0.7-28
    - convert -version
language: java
after_failure:
    - find build/test-results -name TEST-*.xml | xargs -n 1 sh -c 'echo $0 && cat $0'
before_deploy:
    - gradle publish
deploy:
    skip_cleanup: true
    provider: bintray
    file: .bintray.json
    user:
        secure: s/V4o6mhqkt2u+/r6QZqK45/x8tlJcofSHcPDkUzNifkaPnsT3H6AlQB/BXHEWxPOcirXwEFFEXVBkzqNAjCMAjC9/lpeaeytseuCYCOeFPOP+eVBni7/Dv2XnhClfeFkOotHp+elj89+rxag85o8K24h9Ew1BrRL0QFVURenJI1G9dOINJRyNTnwOhf7FES6Itz2+iX38sjnVPoSFQniDCRzsdoDthuFuDFyoyC7Eudecv6hTQXZnszNkyq9JVwEjHoaiH4Ov0OhQQ2klEbvBUKMBEjCl23XPwkWu/rBfLytdKYdJYLx+22kh6oDAF2RrjlRkTloEYMeTOhV2XrlnPAqumMGPLoJXmh3o3302kKZupJSDtyY2Fxa/8rXnqM+bBVHYGPmJGpf9bjg6CzAq5h5zJRj0ZOMElGHVMdG2nZ3jAx54pC924M0hBeI496GrTLXDTW7qitOLrj8pO8AiZrFH4apY6loguUqnFXTrWv2Z4OIBoRThl3orCggBApngiTMnAEwyxqQoMS/WE0aN4t6awLX+R47IBoH/OTK1ZgMQe7q4jiVkCo5gV8lgeeitFM7dYh2n07m06n/FZSUfFxInhWO4jwZnPooqF+Uo5pBEh74aobiSOIt4yDTn02rFbKXKepJqq4t1vlMXmVdHKt2qTJK4NYL+Lm29zEZvE=
    key:
        secure: DZ7+Riwg4rX+CaClbyR3odEUeUpZNVC3lM8AlFuyNg5hYgP1/6npgzrEHljzLxMzQyrxWsc7TYAJjicFBYQKq++jpiDZUi7QQhVc8+VNLmlXwLCaQhXpKd0p+7yJhP1irF2ZGP6YoBqqaTI85zXVNzDZ94NbExNoNn5torGaPhT8X2inM82wwme2anwyTL2/IjjczOrGIFrWpKEWClIV1T28/62ocF6x2qTnZ+xgnPK5qVzg1OL/EYBICRrftcskRbP4VDsOH535JIVkan7O2YRTPeEN0HVxgveSUKY2po5ZAyJluKpeWl5avQVw3kh+tPO8x7GLHqHiLiKxJaqgZBzuIVIz2uXcwkhq2ZKjJX5ysFzfQdn8cvvnkyOr3pSGEL+hYhkhVG6sYv8//dVKaqqTyrEQLJ3F5L76cQsftd+teX3BurGvzaYCNyqx6+SH8/BOGLXf8WQenecCiR+8BstLW0iiMADwIsiglRwHPLKjM3NQTuikUcsRNnnd0BqO6qtvmwBdJqRN31D91aW3LaLSrvjbt4HzDXQ60POMSyzFZHwC79H7q7utxL4h57GBRyM+0mTPc5DjcNeij8yN4nU/Y/5nGlnP7nJXPcClcRJw2bsttBnXOB5/G1zs7YsNwthuJorAHMSb4x3uUyTh2Fv9j0JjVbTjgwKNNovx0Do=
    on:
        all_branches: false
        tags: true
